name: Deploy malerpris.dk

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - name: Publish to registry
        run: |
          docker build --cache-from $ONBUILD -t $ONBUILD -f Dockerfile .
          docker push --all-tags nymann/malerpris.dk
        env:
          ONBUILD: nymann/malerpris.dk:latest
